server:
  port: ${PORT:8083}
logging:
  level:
    web: DEBUG
    org.springframework.jdbc: DEBUG
spring:
  application:
    name: todo-backend
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:5432/postgres"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always