apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: miguelsombrero/todo-app@sha256:1d1985ed2c327ba4dfa88b14eda8f1f7199aafe2c289d23b20a3f49162cf6215
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
