apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: shared-image-claim
      containers:
        - name: todo-app
          image: miguelsombrero/todo-app@sha256:9e018f3d692dd238da0fa99a7b4114b090ee1019c66d535ea40fdfe18655f965
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files
