apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  labels:
    app: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-output-app
          image: miguelsombrero/log-output-app@sha256:f4f1b6f1953d4e1e30603bb47bbb0836ff9adff039d46637d6d617b85376d0f3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
