apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  labels:
    app: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-output-app
          image: miguelsombrero/log-output-app@sha256:72730561baada0f969680728adbda7be7bedec91a70178efce30ca338721112f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
