apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: miguelsombrero/todo-backend@sha256:3cd0c3056fb7b5b4ab1d921bcb894bdd72a27c8d261af99dbba7aabad73149c8
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: todo-backend-config
          - secretRef:
                name: postgres-secret
