apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
  labels:
    app: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: miguelsombrero/ping-pong-app@sha256:950087479b5b16b97f8180d58d9f4597e17cec994605fef04d1dd98f351b6c61
          envFrom:
          - configMapRef:
              name: ping-pong-app-config
          - secretRef:
                name: postgres-secret
