apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
  labels:
    app: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: miguelsombrero/ping-pong-app@sha256:70fe4666aeb6887fbe81b0000c468d7afb0c7c7fbd423479db9fa3482eb40f0e
          envFrom:
          - configMapRef:
              name: ping-pong-app-config
          - secretRef:
                name: postgres-secret
