apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: project
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: shared-image-claim
      containers:
        - name: todo-app
          image: miguelsombrero/todo-app@sha256:1b13c9d7c959b31b2ae3d332a16cf9bb25b53ccacffc48ddd34ea4fe91e9dac7
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files
          envFrom:
          - configMapRef:
              name: todo-app-config
