file:
  path: ${FILE_PATH:/usr/src/app/files/pingpong.txt}
server:
  port: ${PORT:8092}
logging:
  level:
    web: DEBUG
    org.springframework.jdbc: DEBUG
spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:5432/postgres"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql:
    init:
      mode: always