apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-logs-claim
        - name: log-config-volume
          configMap:
            name: log-config
      containers:
        - name: log-output-writer-app
          image: miguelsombrero/log-output-writer-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files

        - name: log-output-reader-app
          image: miguelsombrero/log-output-reader-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files
          - name: log-config-volume
            mountPath: /usr/src/app/files/config
          envFrom:
          - configMapRef:
              name: log-config
